function createBarGraph(ymatrix1, xgroupsLabels, barLegends, titleName, ylabelTxt, xlabelTxt )
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 31-Jan-2014 14:50:05

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'XTickLabel',xgroupsLabels,...
    'XTick',1:length(xgroupsLabels));
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'Parent',axes1);

% Create title
title(titleName);

% Create xlabel
xlabel(xlabelTxt);

%set legend
legend(barLegends,'Location', 'SouthOutside');

% Create ylabel
ylabel(ylabelTxt);

