function createBoxPlot(ymatrix1, boxLengends, titleName, ylabelTxt, xlabelTxt )
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 31-Jan-2014 14:50:05

for i=1:length(boxLengends)
    boxLengends{i} = strjoin(acronym(boxLengends{i}),'.');
end;

% Create multiple lines using matrix input to bar
figure, boxplot(ymatrix1,boxLengends)


% Create title
title(titleName);

% Create xlabel
xlabel(xlabelTxt);

% Create ylabel
ylabel(ylabelTxt);

